name: Java CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linter:
    name: Lint (Checkstyle - GoogleStyle)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Ensure Gradle cache directories exist
        run: |
          mkdir -p ~/.gradle/caches
          mkdir -p ~/.gradle/wrapper
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle', '**/gradle-wrapper.properties') }}
      - name: Run Checkstyle (Google Style)
        uses: dbelyaev/action-checkstyle@v1.21.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          checkstyle_config: google_checks.xml
          level: error
          fail_level: error

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: linter
    if: needs.linter.result == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Ensure Gradle cache directories exist
        run: |
          mkdir -p ~/.gradle/caches
          mkdir -p ~/.gradle/wrapper
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle', '**/gradle-wrapper.properties') }}
      - name: Create logs directory
        run: mkdir -p ./logs
      - name: Run Unit Tests
        run: ./gradlew test --no-daemon | tee ./logs/unit-test.log
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: ./logs/unit-test.log
      - name: Run Stress Tests
        run: ./gradlew stressTest --no-daemon | tee ./logs/stress-test.log
      - name: Upload Stress Test Results
        uses: actions/upload-artifact@v4
        with:
          name: stress-test-results
          path: ./logs/stress-test.log
      - name: Upload Gradle Problems Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-problems-report
          path: ./build/reports/problems/